# data
# task: assembling-kits-3dtoolkit
# n_rotations: 360                  # Number of rotation classifications
log_dir: '.'                      # ./logs/{task}-{n_rotations}-{n_demos}-0/{date}_{model}{model_postfix}
test_dir: './test/'               # ./test/{model}{model_postfix}/{task}-{n_rotations}-{n_demos}-0-{n_steps}
data_dir: './data/'
checkpoint_dir: './checkpoints/'  # ./checkpoints/{task}-{n_rotations}-{n_demos}-0/{model}{model_postfix}/...

# model
# model: equ                        # model opt: [equ, femi, semi, #non, tail, grconv, equ_grconv, so2]
# model_postfix: ''                 # Ckpt saved in 'checkpoints_{so2-7}' folder
                                  # Test saved in 'test_{so2-7}' folder

init: True                       # Weight initialization
load: 0                           # Pre-trained model iter; 0 means no loading

# equ model
equ:
  position:
    N: 6
    lite: True
    label_type: 2
    label_smooth: 0.0
    label_radius: 1
    label_sigma: 1
  angle:
    lite: True
    label_type: 2
    label_smooth: 0.0
    label_radius: 1
    label_sigma: 1
  transport:
    N: 6
    lite: True
    label_type: 2
    label_smooth: 0.0
    label_radius: 1
    label_sigma: 1

so2:
  position:
    irrep: 3                      # irreps: [0, max_irreps]
    sample: 16                    # sample no. for ift conversion
    lite: True
    label_type: 2                 # [gaussian, rectangle, pulse, triangle]
    label_smooth: 0.0
    label_radius: 1
    label_sigma: 1
  angle:
    irrep: 6                      # irreps: [0, max_irreps]
    sample: 36                    # sample no. for ift conversion
    lite: True
    label_type: 2                 # [gaussian, rectangle, pulse, triangle]
    label_smooth: 0.0
    label_radius: 1
    label_sigma: 1
  transport:
    irrep: 3                      # irreps: [0, max_irreps]
    sample: 16                    # sample no. for ift conversion
    lite: True
    label_type: 2                 # [gaussian, rectangle, pulse, triangle]
    label_smooth: 0.0
    label_radius: 1
    label_sigma: 1

# training & testing
# gpu_id: 0                         # -1 means cpu
# n_demos: 100                      # demo no for model training
# n_steps: 10000                    # total training iterations
# interval: 5000                    # checkpoint savings
n_runs: 1                         # runs of training (different seeds)
# logging: False                    # logging the training info

# testing
root_dir: '.'
assets_root: './raven/assets'
# disp: True
continuous: False                 # not implemented
shared_memory: False              # not important; related to pybullet
# entire: False                     # not important


